CREATE TABLE IF NOT EXISTS shopping_lists (
	   id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	   description varchar(255) NOT NULL DEFAULT '',
	   created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	   modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	   deleted BOOLEAN NOT NULL DEFAULT 0
) auto_increment=1000 ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS shopping_list_items (
	   id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	   shopping_list_id int NOT NULL,
	   description varchar(255) NOT NULL,
	   done BOOLEAN NOT NULL DEFAULT 0,
	   modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	   deleted BOOLEAN NOT NULL DEFAULT 0,
	   FOREIGN KEY fk_shopping_lists(shopping_list_id)
	   REFERENCES shopping_lists(id)
	   ON UPDATE CASCADE
	   ON DELETE CASCADE
) auto_increment=1000 ENGINE=InnoDB DEFAULT CHARSET=utf8;
